services:
  content-db:
    image: 'postgres:latest'
    container_name: content-db
    environment:
      - 'POSTGRES_DB=content_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
    volumes:
      - './postgres/content-db:/var/lib/postgresql'
  auth-db:
    image: 'postgres:latest'
    container_name: auth-db
    environment:
      - 'POSTGRES_DB=auth_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5434:5432'
    volumes:
      - './postgres/auth-db:/var/lib/postgresql'

#services:
#  postgresql:
#    image: postgres
#    restart: always
#    container_name: postgresql
#    ports:
#      - "15432:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: test
#    volumes:
#      #      - ./data:/var/lib/postgresql/data
#      - ./data:/var/lib/postgresql